# Every Dockerfile starts with a FROM, which describes what image we are building our image from.
FROM rocker/r-ver:4.0.3

# RUN useradd -ms /bin/bash airflow

# USER airflow

# WORKDIR /home/airflow/analysis

CMD ["/bin/bash"]

